#!/bin/bash

# Create an Artisan command alias that can be run from anywhere in the
# filesystem. We do not do this using a bash alias or function because they
# wouldn't be available to `podman run` or `podman-compose exec`.
CURRENT_DIR=$PWD

app_root=${APP_PROJECT_ROOT:-/var/www/html}
cd ${app_root}
php artisan "$@"

cd $CURRENT_DIR
